### ISSUE TITLE
Loading materials at runtime in an exported project does not find the file correctly

### ISSUE THREAD

**Issue by RisingThumb** [func-godot/func_godot_plugin#14]
Following related discord discussion.

In `func_godot_texture_loader.gd`, we are calling `FileAccess.file_exists()`, which fails as the materials are converted into Godot's equivalent binary file to improve exported binary sizes and this doesn't map to the new file name.

Fixing this should be a case of removing this file check, and using `load()` instead, as this properly maps to the material resource. If it doesn't exist, an empty resource is returned. See load documentation here https://docs.godotengine.org/en/stable/classes/class_resourceloader.html#class-resourceloader-method-load

**Comment by RisingThumb** [comment]
@RhapsodyInGeek has this issue been resolved by https://github.com/func-godot/func_godot_plugin/commit/e711865f0b9343beb37f7bdd7b7226f8914027e2 ?

**Comment by RhapsodyInGeek** [comment]
Resolved by e711865
