### ISSUE TITLE
Add support for Valve Source Engine 2 using...

### ISSUE THREAD

**Issue by MachinistJohn** [func-godot/func_godot_plugin#20]
this plugin https://github.com/H2xDev/GodotVMF

**Comment by RhapsodyInGeek** [comment]
It's a really cool plugin, but it's very different from FuncGodot to the point where I don't see being able to feasibly integrate their processes into FuncGodot's. We'd need a different design to support VMF, it's unfortunately not as simple as slapping another plugin onto FuncGodot.
