### ISSUE TITLE
"Use Trenchbroom Group Hierarchy" causes unresolvable hang on build unless  "Print Profiling Data" enabled. 

### ISSUE THREAD

**Issue by amdevgwen** [func-godot/func_godot_plugin#22]
Godot Version: Godot 4.3 Beta 2
Odd behaviour when FuncGodotMap attempts to build a map with use Trenchbroom Groups Hierarchy is enabled while no entities are set to a non-default layer. FuncGodot hangs without finishing the build and it's last log entry is "resolve_trenchbroom_group_hierarchy"
This behaviour does not appear when "Print Profiling Data" setting is enabled.

**Comment by RhapsodyInGeek** [comment]
Unable to reproduce in this bug. Please provide a minimum reproduction project in case you experience this issue again.
