### ISSUE TITLE
Godot Editor crashes on map re-build after modifying map with map siblings referencing map children via @export vars

### ISSUE THREAD

**Issue by azur-wolf** [func-godot/func_godot_plugin#24]
When have a `FuncGodotMap` on a scene, and the map  has any sibling node with `@export` vars referencing child nodes of the map.
If build the map again and try to save Godot Editor crashes.

The cause is due to deleting some entities within TrenchBroom, so the "hierarchy" changes.

**Comment by RhapsodyInGeek** [comment]
This is expected behavior honestly, and not anything we can actually do anything about. You shouldn't have hard references to nodes in the map in any tool scripts (or any nodes for that matter) unless you can guarantee those nodes will exist. You'll need to work around it.
