### ISSUE TITLE
ModelPointClass will generate a gdignore regardless of whether "generate_gd_ignore_file" is true or false.

### ISSUE THREAD

**Issue by LukesOffline** [func-godot/func_godot_plugin#29]
I have a **ModelPointClass** in my game project, using func_godot for mapping. I like to be able to access all of my folders from within Godot, so I set the "**generate_gd_ignore_file**" boolean to false within the ModelPointClass resource.
![image](https://github.com/user-attachments/assets/8ace092d-7ba8-4ed0-bfaf-b8863ea30d0a)
Even with this set, func_godot is insistent in still producing a .gdignore file within my Trenchbroom models folder.

**Comment by RhapsodyInGeek** [comment]
Should be resolved by 2fba771
