### ISSUE TITLE
let TB layers marked as disabled discard their contents on map build, even if TB groups hierarchy disabled

### ISSUE THREAD

**Issue by azur-wolve** [func-godot/func_godot_plugin#31]
**_feature request_**

![Screenshot from 2024-08-31 06-06-15](https://github.com/user-attachments/assets/d25db275-7d07-4bfa-90f6-145e7af704c2)

that would allow discard auxiliary layers used for prefabs, references, placeholder maps, etc

independently that if `FuncGodotMapSettings.use_trenchbroom_groups_hierarchy` is true or false

**Comment by RhapsodyInGeek** [comment]
I'm not against this proposal, but it's a pretty complicated ask. See this post here, as it's related:
https://github.com/func-godot/func_godot_plugin/issues/30#issuecomment-2327469012
