### ISSUE TITLE
disabled entities on TB layers still invoked on map build

### ISSUE THREAD

**Issue by azur-wolve** [func-godot/func_godot_plugin#39]
if a `tb_layer` that is disabled and marked as hidden (eye icon) from TB (using TB groups hierarchy)
FuncGodot still calls its `_func_godot_apply_properties()` and `_func_godot_build_complete()`

discovered when instancing nodes during map build in the editor from fgd generated nodes that were on disabled layers
Those dont appear on the scene dock but still on background seems to be

expected behavior to be disabled

**Comment by RhapsodyInGeek** [comment]
Resolved by #45
