### ISSUE TITLE
Allow collapse all FuncGodotMap child nodes after map build

### ISSUE THREAD

**Issue by azur-wolf** [func-godot/func_godot_plugin#40]
Every time a map is built all its children are unfolded letting the scene dock being a bit chaotic.
So every time press go `FuncGodotMap` `RMB` → "Expand/Collapse Branch"

Could be an option on the map to let it collapse by default?

**Comment by sinewavey** [comment]
The godot editor can already do this.
Control shift click the topmost section you'd like to utterly collapse.

**Comment by RhapsodyInGeek** [comment]
They're also not always unfolded. If you hold shift when collapsing the tree, it collapses all branches in the tree as well. When you build the map after doing this it won't open up the tree again until you manually do so first.
