### ISSUE TITLE
Trenchbroom groups use absolute positioning instead of relative when built

### ISSUE THREAD

**Issue by cybernaut4** [func-godot/func_godot_plugin#5]
# Situation

I use TrenchBroom group's hierarchy. With this, I can write point entities that operate with various types of sibling entities within the group.

My scene is comprised of more than one map: each represents a single floor.

# Problem

Every node is positioned correctly, save for the group hierarchies which use absolute positioning in the scene instead of being relative to FuncGodotMap's.

✔Building from (0,0,0):
![image](https://github.com/func-godot/func_godot_plugin/assets/68290346/962aacc8-595e-40d7-973b-b96be3f8cb3b)

❌Building from anywhere else (0,97,-32):
![image](https://github.com/func-godot/func_godot_plugin/assets/68290346/25188a72-18c7-4fa1-b33c-147f55710493)

# Solution

Have the group hierarchies position relatively to the FuncGodotMap node.

# Workarounds

### 1 - Scenes
It's possible to put each FuncGodotMap in their own scenes. This way the scene will have each their own absolute positioning for group hierarchies, but switching between them too often can be disorienting after a while (eg. to check if the structure coincides with each other after building them).
### 2 - Zero positioning
1. Move the additional FuncGodotMap to position zero.
2. Hide the main FuncGodotMap.
3. Build it (as many times as needed).
4. Once you're done building/iterating/working (with) it, return the aforementioned FuncGodotMap to its intended place and show the main FuncGodotMap.

**Comment by RhapsodyInGeek** [comment]
Looking into it, it looks like the groups are all actually positioned at the FuncGodotMap's position and what's really going on is the mesh generation is happening at the offset position for other layers. It gets a little weirder when the groups are inside layers. Layers themselves are placed at the FuncGodotMap's position.

Unfortunately, the fix seems like it'll be more complicated than just "have group hierarchies' position relative to FuncGodotMap's".

**Comment by RhapsodyInGeek** [comment]
Resolved by 9a8da22
