### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by Visssarion** [func-godot/func_godot_plugin#9]
![image](https://github.com/func-godot/func_godot_plugin/assets/46628714/5c665ae5-76b5-4ca3-a917-b5786d39b188)
Getting Started -> Textures ->Clip and Skip Textures -> Mapping for Quake Godot
> We started off this manual with the point that [FuncGodot is not a BSP compiler](https://func-godot.github.io/func_godot_docs/FuncGodot%20Manual/index.html#FuncGodotIsNotABspCompiler). If we map like we do in traditional Quake mapping...

This link: https://func-godot.github.io/func_godot_docs/FuncGodot%20Manual/index.html#FuncGodotIsNotABspCompiler
doesn't work

**Comment by RhapsodyInGeek** [comment]
Thanks for the report! Resolved with https://github.com/func-godot/func_godot_docs/commit/5c478a695da7ec4eefe651f332d9050c663ad1de.
